### PR TITLE
Addition of welcome screen mockup

### PR DESCRIPTION
**Pull request by abhushanaj**
#21 

Info Screen Mockup

Info_Screen

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
Hey ! Really nice effort. You should remove the 'NEXT' text, we will add a button instead of that, so its a XML thing. Also, I would like if the photo is related to crop leaf analyzing than what it is now. And in place of text below the image, we should use 'tagline' or 'motive' of app/ what it will do rather than 'welcome to....'. But effort wise, you have done great. Please incorporate these changes.

**Comment by abhushanaj** [comment]
> Hey ! Really nice effort. You should remove the 'NEXT' text, we will add a button instead of that, so its a XML thing. Also, I would like if the photo is related to crop leaf analyzing than what it is now. And in place of text below the image, we should use 'tagline' or 'motive' of app/ what it will do rather than 'welcome to....'. But effort wise, you have done great. Please incorporate these changes.

Oh! Actually I was making one more second screen for that, which display tagline and info. I was thinking it will display after we hit next and then after that screen we can go to the actual application . I was thinking this like those info details which comes up in app when we install for first time we can can skip if we want! I think I understood issue wrong Sir

**Comment by tanishq9** [comment]
Don't put tagline and info on one page. Make it like : tagline on first page and info on the second. And yes, we will add skip,next and back buttons in XML, so you have to focus on design and content part.

**Comment by abhushanaj** [comment]
> Don't put tagline and info on one page. Make it like : tagline on first page and info on the second. And yes, we will add skip,next and back buttons in XML, so you have to focus on design and content part.

Okay Got it Sir. I will make the changes 👍

**Comment by abhu-A-J** [comment]
@tanishq9 Sir, the updated version. Is this okay??
Welcome Screen-2

**Comment by abhushanaj** [comment]
> > Don't put tagline and info on one page. Make it like : tagline on first page and info on the second. And yes, we will add skip,next and back buttons in XML, so you have to focus on design and content part.
> 
> Okay Got it Sir. I will make the changes 👍

Made the update Sir, you may review again!

**Review by tanishq9 — COMMENTED** [review]
Since you have mentioned the logo on the top, so don't write CROP AI again below the image and instead of that write : Your Crop Analyzer App (in all caps) or something like this and instead of the paragraph of the features, try to write it in points like : 

-  Diagnose pest damage .....
-  Suggest treatment measures 

This will make it look more concise and to the point.

**Comment by tanishq9** [comment]
And since your design had info, so it was for 2nd page of on boarding ?
We can design the 1st page later when we get the final logo and tagline.

**Comment by abhushanaj** [comment]
> Since you have mentioned the logo on the top, so don't write CROP AI again below the image and instead of that write : Your Crop Analyzer App (in all caps) or something like this and instead of the paragraph of the features, try to write it in points like :
> 
> * Diagnose pest damage .....
> * Suggest treatment measures
> 
> This will make it look more concise and to the point.

Okay got it! Will change it!

**Comment by abhushanaj** [comment]
> And since your design had info, so it was for 2nd page of on boarding ?
> We can design the 1st page later when we get the final logo and tagline.

Yes Sir, this would be second page, since I need some more idea's on welcome page! I'll update the readme for this to avoid confusion

**Comment by abhushanaj** [comment]
> > And since your design had info, so it was for 2nd page of on boarding ?
> > We can design the 1st page later when we get the final logo and tagline.
> 
> Yes Sir, this would be second page, since I need some more idea's on welcome page! I'll update the readme for this to avoid confusion

You may review now Sir. 😃

**Review by tanishq9 — COMMENTED** [review]
Wonderful !

**Pull request merged**
