### PR TITLE
Android Q: App not working bug fixed(API Level 29)

### LINKED ISSUE #56: Image Analyser not working [Android Q Bug]
Device: Oneplus 6
OS: Android 10(Q) Oxygen OS

After installation, when I tried to test the app I noticed two problems:

- After selecting the image from the gallery, as soon as we return to the app there was an empty screen with no preview of any kind of the image. I'm not aware if it's not implemented or it's a bug. 

empty screen after upload

- The second problem is that regardless of the Internet Connection, Toast message always shows "no Internet Connection".

no internet problem

### PR DESCRIPTION
**Pull request by CapTen101**
Fixes #56 

- ParcelFileDescriptor is used to fix the EAccess bug in API Level 29 and above.
- Also I upgraded the older version of the gradle dependencies
- Used Image:
leaf

The APP is working fine: (Though it was a money plant's leaf not potato :😅)
- Obtained results:
leaf

### CODE REVIEW

**Comment by CapTen101** [comment]
@tanishq9 Why all the checks have failed? I checked them and it shows `Resource not accessible by integration`.

**Comment by tanishq9** [comment]
Yes, there is some issue with greeting action, it will be fixed soon.

**Review by tanishq9 — COMMENTED** [review]
The changes are working as expected. Well done.

**Comment by tanishq9** [comment]
You can ignore the crop disease predicted, the dataset that we trained on probably didn't contain any money plant leaf images.

**Comment by CapTen101** [comment]
Ok, cool.
Thanks! @tanishq9 
I would love to work on other issues too(if any) pop up. 😄

**Pull request merged**
