### PR TITLE
Addition of onboarding screen mockup

### PR DESCRIPTION
**Pull request by Sapna2001**
Issue #21 
I have designed the home page, info page, and instruction page using adobe xd.
Home Page
Home Page

Information Page
Info Page

Instruction Page
Instruction Page

### CODE REVIEW

**Comment by Sapna2001** [comment]
Please review them and suggest changes.

**Review by tanishq9 — COMMENTED** [review]
Good effort but the designs are not at all attractive, please have a look at other designs as well. Also, the 2nd page of on boarding is finalized, and for the first page, the tagline is being decided by the participants on slack.

**Comment by Sapna2001** [comment]
I will change the design and make a PR again.

**Comment by tanishq9** [comment]
Sure.

**Pull request closed without merging**
