### PR TITLE
Added permission

### PR DESCRIPTION
**Pull request by abhishekgupta368**
**Issue**:  Add file read and write access permission in the manifest file. #3

file:
manifest.xml modified

feature implemented:
added permission in android manifest

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
You have changed 5 files and not explained any of the changes in the pull request. Also, there is no need to specify maximum target version in manifest, if you think so, then please justify and you have added only write permission, I clearly mentioned we need both read and write permissions.

**Review by tanishq9 — COMMENTED** [review]
Don't change the codeStyles file, it will make the project heavy. You can uninstall the plugin in your android studio.

**Comment by abhishekgupta368** [comment]
Sure

**Review by tanishq9 — COMMENTED** [review]
Finally. Well done !

**Pull request merged**
