### PR TITLE
Logos added

### PR DESCRIPTION
**Pull request by Sapna2001**
Issue #24 .
I have added two logos.
Logo 1
Sapna logo-1

Logo 2
Sapna logo-2

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
For the first logo, remove the text, and make both the logos have transparent background.

**Comment by Sapna2001** [comment]
Logo 1
Sapna logo-1

Logo 2
Sapna logo-2

**Comment by tanishq9** [comment]
Nice work. The second logo is amazing. Can you change the light blue, pinkish color in the above 2 logos to shades of green. We want to keep the theme to be green, so that's why,

**Comment by Sapna2001** [comment]
Logo 2
Sapna logo-2

**Comment by tanishq9** [comment]
Awesome. Merging it.

**Pull request merged**
