### PR TITLE
Screenshot file attached 

### PR DESCRIPTION
**Pull request by rasacharjee**
The Screenshots attached are when the app was tested on Device: Realme 3 Pro Android Version: 10

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
Delete all the files except for your screenshots markdown file.

**Review by tanishq9 — COMMENTED** [review]
You have deleted all the files ! Couldn't you just include your own screenshot in the PR.

**Comment by rasacharjee** [comment]
My mistake. Please discard this request.

**Comment by rasacharjee** [comment]
I could not restore the files deleted so , please discard this request and please consider another proper pull request created.

**Pull request closed without merging**
