### PR TITLE
OnBoarding Screen Design Mockup

### PR DESCRIPTION
**Pull request by Satyam3976**
#21 
satyam-landingPage
Designed in Photoshop Can provide the PSD file if needed for changes

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
Either .png or .svg not .jpg, other image extensions won't scale well even .png.

**Comment by Satyam3976** [comment]
> Either .png or .svg not .jpg, other image extensions won't scale well even .png.

@tanishq9 Sorry for that, I had changed the extension, please have a look at it.

**Review by tanishq9 — COMMENTED** [review]
You haven't mentioned if this "on boarding screen mockup" is for first page/second page.etc and also how do you plan to add to it ? Plus, the full page is never covered in "on boarding", try to place the text in the center of screen.

**Comment by Satyam3976** [comment]
It is the first page. Actually I designed in this way, and I can't put everything in the centre. So can I put that image on the left-upper part only as it is now, and reduce the font size and put it in centre

**Comment by tanishq9** [comment]
We don't want to show info on 1st page, 1st page has to be reserved for tagline and logo, 2nd page for info, 3rd page is a 'get started' page. As of now 2nd page is finalized, for 1st and 3rd page, wait for 3-4 days until some more features are implemented in the android app.

**Comment by Satyam3976** [comment]
Okay, I'll wait and then design the 1st and 3rd page. So It's fine for 2nd page or shall u want any changes in this page?

**Pull request merged**
